name: Publish Docker
on:
  release:
    types:
      - published

concurrency: release

env:
  REGISTRY: ghcr.io
  GIT_AUTHOR_NAME: eg-oss-ci
  GIT_AUTHOR_EMAIL: oss@expediagroup.com
  GIT_COMMITTER_NAME: eg-oss-ci
  GIT_COMMITTER_EMAIL: oss@expediagroup.com

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          echo REF: $GITHUB_REF_NAME
