name: Publish Docker
on:
  release:
    types:
      - published

concurrency: release

env:
  REGISTRY: ghcr.io
  GIT_AUTHOR_NAME: eg-oss-ci
  GIT_AUTHOR_EMAIL: oss@expediagroup.com
  GIT_COMMITTER_NAME: eg-oss-ci
  GIT_COMMITTER_EMAIL: oss@expediagroup.com

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          SANS_VERSION=${GITHUB_REF_NAME#v*}
          MAJOR=$(echo $SANS_VERSION | cut -d. -f1)
          MINOR=$(echo $SANS_VERSION | cut -d. -f2)
          PATCH=$(echo $SANS_VERSION | cut -d. -f3)
          echo $MAJOR $MINOR $PATCH
