name: Publish Docker
on:
  release:
    types:
      - published

concurrency: release

env:
  REGISTRY: ghcr.io
  GIT_AUTHOR_NAME: eg-oss-ci
  GIT_AUTHOR_EMAIL: oss@expediagroup.com
  GIT_COMMITTER_NAME: eg-oss-ci
  GIT_COMMITTER_EMAIL: oss@expediagroup.com

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test

      - name: Parse release version
        run: |
          VERSION=${GITHUB_REF_NAME#v*}
          echo "MAJOR=$(echo $VERSION | cut -d. -f1)" >> $GITHUB_ENV
          echo "MINOR=$(echo $VERSION | cut -d. -f2)" >> $GITHUB_ENV
          echo "PATCH=$(echo $VERSION | cut -d. -f3)" >> $GITHUB_ENV
          echo $MAJOR $MINOR $PATCH

      - name: Test release version
        run: |
          echo {{ env.$MAJOR }} . {{ env.$MINOR }} . {{ env.$PATCH}}
